# Generated by Django 5.0 on 2023-12-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_image_product_image1_remove_product_thumbnail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
