# Generated by Django 5.0 on 2023-12-11 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableProductSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='product.product')),
            ],
            options={
                'ordering': ('product',),
            },
        ),
    ]
