# Generated by Django 4.2.1 on 2023-12-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_availableproductsize_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdeliveryinformation',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientDeliveryInformation',
        ),
    ]
