# Generated by Django 5.0 on 2024-01-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_clientdeliveryinformation_client_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bigcategory',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('id',), 'verbose_name': 'Размер одежды', 'verbose_name_plural': 'Размеры одежды'},
        ),
        migrations.AlterField(
            model_name='productsize',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
